timer:
  time: 8
setting:
  isRandomBlockDropsEnabled: false
  isSuperRandomBlockDropsEnabled: false
  isRandomMobDropsEnabled: false
  isSuperRandomMobDropsEnabled: false
  isRandomMobSpawnsEnabled: false
  isSuperRandomMobSpawnsEnabled: false